# Generated by Django 3.1.1 on 2020-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='lunch_finish',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='lunch_start',
            field=models.TimeField(),
        ),
    ]
