# Generated by Django 3.1.1 on 2020-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200906_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vaccine_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
