# Generated by Django 3.1.1 on 2020-09-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_vaccinetype'),
        ('appointment', '0003_appointment_vaccine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vaccine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.vaccinetype'),
        ),
    ]
