# Generated by Django 3.1.1 on 2020-09-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_vaccinetype'),
        ('appointment', '0004_auto_20200906_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.vaccinetype'),
        ),
    ]
