# Generated by Django 3.1.1 on 2020-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200906_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
